import java.lang.reflect.Array;
import java.util.ArrayList;

public class appDataBase {

    ArrayList<String> Alzheimers = new ArrayList<String>();
    Alzheimers.add("Benzgalantamine");
    Alzheimers.add("Donepezil");
    Alzheimers.add("Namzaric");
    Alzheimers.add("Galantamine");
    Alzheimers.add("Rivastigmine");
    Alzheimers.add("Memantine");
    Alzheimers.add("Brexpiprazole");
    Alzheimers.add("Lecanemab");
    Alzheimers.add("Donanemab");
    Alzheimers.add("Citalopram");
    Alzheimers.add("Escitalopram");
    Alzheimers.add("Sertraline");

    ArrayList<String> VascularDementia = new ArrayList<String>();
    VascularDementia.add("Benzgalantamine");
    VascularDementia.add("Donepezil");
    VascularDementia.add("Namzaric");
    VascularDementia.add("Galantamine");
    VascularDementia.add("Rivastigmine");
    VascularDementia.add("Memantine");
    VascularDementia.add("Brexpiprazole");
    VascularDementia.add("Aspirin");
    VascularDementia.add("Clopidogrel");
    VascularDementia.add("Aggrenox");
    VascularDementia.add("Citalopram");
    VascularDementia.add("Escitalopram");
    VascularDementia.add("Fluoxetine");
    VascularDementia.add("Fluvoxamine");
    VascularDementia.add("Paroxetin");
    VascularDementia.add("Vilazodone");

    ArrayList<String> Schizophrenia = new ArrayList<String>();
    Schizophrenia.add("Benzgalantamine");
    Schizophrenia.add("Donepezil");
    Schizophrenia.add("Namzaric");
    Schizophrenia.add("Galantamine");
    Schizophrenia.add("Rivastigmine");
    Schizophrenia.add("Haloperidol");
    Schizophrenia.add("Perphenazine");
    Schizophrenia.add("Risperidone");
    Schizophrenia.add("Quetiapine");
    Schizophrenia.add("Olanzapine");
    Schizophrenia.add("Ziprasidone");
    Schizophrenia.add("Paliperidone");
    Schizophrenia.add("Aripiprazole");
    Schizophrenia.add("Clozapine");
    Schizophrenia.add("Sertraline");
    Schizophrenia.add("Fluoxetine");
    Schizophrenia.add("Citalopram");
    Schizophrenia.add("Escitalopram");
    Schizophrenia.add("Venlafaxine");
    Schizophrenia.add("Duloxetine");
    Schizophrenia.add("Lorazepam");
    Schizophrenia.add("Clonazepam");

    ArrayList<String> Epilepsy = new ArrayList<String>();
    Epilepsy.add("Carbamazepine");
    Epilepsy.add("Lamotrigine");
    Epilepsy.add("Levetiracetam");
    Epilepsy.add("Valproic Acid");
    Epilepsy.add("Topiramate");
    Epilepsy.add("Oxcarbazepine");
    Epilepsy.add("Zonisamide");
    Epilepsy.add("Clonazepam");
    Epilepsy.add("Clobazam");
    Epilepsy.add("Phenobarbital");
    Epilepsy.add("Phenytoin");
    Epilepsy.add("Gabapentin");
    Epilepsy.add("Lacosamide");
    Epilepsy.add("Pregabalin");

    ArrayList<String> Parkinsons = new ArrayList<String>();
    Parkinsons.add("Benzgalantamine");
    Parkinsons.add("Donepezil");
    Parkinsons.add("Namzaric");
    Parkinsons.add("Galantamine");
    Parkinsons.add("Rivastigmine");
    Parkinsons.add("Carbidopa");
    Parkinsons.add("Levodopa");
    Parkinsons.add("Citalopram");
    Parkinsons.add("Escitalopram");
    Parkinsons.add("Fluoxetine");
    Parkinsons.add("Sertraline");

    ArrayList<String> LewyBodyDementia = new ArrayList<String>();
    LewyBodyDementia.add("Donepezil");
    LewyBodyDementia.add("Rivastigmine");
    LewyBodyDementia.add("Galantamine");
    LewyBodyDementia.add("Quetiapine");
    LewyBodyDementia.add("Clozapine");
    LewyBodyDementia.add("Pimavanserin");
    LewyBodyDementia.add("Carbidopa-Levodopa");
    LewyBodyDementia.add("Clonazepam");
    LewyBodyDementia.add("Memantine");

    ArrayList<String> MultipleSclerosis = new ArrayList<String>();
    MultipleSclerosis.add("Myrbetriq");
    MultipleSclerosis.add("Ampyra");
    MultipleSclerosis.add("Baclofen");
    MultipleSclerosis.add("Botox");
    MultipleSclerosis.add("Dantrolene");
    MultipleSclerosis.add("Oxybutynin");
    MultipleSclerosis.add("Vesicare");
    MultipleSclerosis.add("Amantadine");
    MultipleSclerosis.add("Modafinil");
    MultipleSclerosis.add("Gabapentin");
    MultipleSclerosis.add("Pregabalin");
    MultipleSclerosis.add("Duloxetine");
    MultipleSclerosis.add("Prednisone");

    ArrayList<String> PersonalityDisorder = new ArrayList<String>();
    PersonalityDisorder.add("Sertraline");
    PersonalityDisorder.add("Fluoxetine");
    PersonalityDisorder.add("Citalopram");
    PersonalityDisorder.add("Escitalopram");
    PersonalityDisorder.add("Paroxetine");
    PersonalityDisorder.add("Venlafaxine");
    PersonalityDisorder.add("Duloxetine");
    PersonalityDisorder.add("Bupropion");
    PersonalityDisorder.add("Lithium");
    PersonalityDisorder.add("Divalproex");
    PersonalityDisorder.add("Lamotrigine");
    PersonalityDisorder.add("Carbamazepine");
    PersonalityDisorder.add("Risperidone");
    PersonalityDisorder.add("Quetiapine");
    PersonalityDisorder.add("Olanzapine");
    PersonalityDisorder.add("Aripiprazole");
    PersonalityDisorder.add("Clonazepam");
    PersonalityDisorder.add("Lorazepam");
    PersonalityDisorder.add("Alprazolam");

    ArrayList<String> FrontotemporalDementia = new ArrayList<String>();
    FrontotemporalDementia.add("Citalopram");
    FrontotemporalDementia.add("Escitalopram");
    FrontotemporalDementia.add("Sertraline");
    FrontotemporalDementia.add("Fluoxetine");
    FrontotemporalDementia.add("Trazodone");
    FrontotemporalDementia.add("Olanzapine");
    FrontotemporalDementia.add("Quetiapine");
    FrontotemporalDementia.add("Bupropion");
    FrontotemporalDementia.add("Methylphenidate");
    FrontotemporalDementia.add("Levodopa");

    ArrayList<String> Huntingtons = new ArrayList<String>();
    Huntingtons.add("Tetrabenazine");
    Huntingtons.add("Deutetrabenazine");
    Huntingtons.add("Valbenazine");
    Huntingtons.add("Haloperidol");
    Huntingtons.add("Olanzapine");
    Huntingtons.add("Risperidone");
    Huntingtons.add("Amantadine");
    Huntingtons.add("Sertraline");
    Huntingtons.add("Citalopram");
    Huntingtons.add("Paroxetine");
    Huntingtons.add("Clonazepam");
    Huntingtons.add("Diazepam");
    Huntingtons.add("Trazodone");
    Huntingtons.add("Aripiprazole");
    Huntingtons.add("Olanzapine");
    Huntingtons.add("Haloperidol");
    Huntingtons.add("Divalproex");
    Huntingtons.add("Carbamazepine");
    Huntingtons.add("Lamotrigine");

    ArrayList<String> WernickeKorsakoffSyndrome = new ArrayList<String>();
    WernickeKorsakoffSyndrome.add("Thiamine");
    WernickeKorsakoffSyndrome.add("Donepezil");
    WernickeKorsakoffSyndrome.add("Memantine");
    WernickeKorsakoffSyndrome.add("Paroxetine");

    ArrayList<String> PosteriorCorticalAtrophy = new ArrayList<String>();
    PosteriorCorticalAtrophy.add("Donepezil");
    PosteriorCorticalAtrophy.add("Rivastigmine");
    PosteriorCorticalAtrophy.add("Galantamine");
    PosteriorCorticalAtrophy.add("Memantine");

    ArrayList<String> BrainTumors = new ArrayList<String>();
    BrainTumors.add("Meningioma");
    BrainTumors.add("Metastatic");
    BrainTumors.add("Glioblastoma");

    ArrayList<String> Meningioma = new ArrayList<String>();
    Meningioma.add("Bevacizumab");
    Meningioma.add("Hydroxyurea");
    Meningioma.add("Mifepristone");
    Meningioma.add("Sandostatin");
    Meningioma.add("Temozolomide");
    Meningioma.add("Levetiracetam");
    Meningioma.add("Phenytoin");

    ArrayList<String> Metastatic = new ArrayList<String>();
    Metastatic.add("Dexamethasone");
    Metastatic.add("Prednisone");
    Metastatic.add("Levetiracetam");
    Metastatic.add("Phenytoin");
    Metastatic.add("Carbamazepine");
    Metastatic.add("Pembrolizumab");
    Metastatic.add("Nivolumab");
    Metastatic.add("Ipilimumab");
    Metastatic.add("Temozolomide");
    Metastatic.add("Lomustine");
    Metastatic.add("Procarbazine");
    Metastatic.add("Vincristine");

    ArrayList<String> Glioblastoma = new ArrayList<String>();
    Glioblastoma.add("Temozolomide");
    Glioblastoma.add("Bevacizumab");
    Glioblastoma.add("Lomustine");
    Glioblastoma.add("Carmustine");
    Glioblastoma.add("Dexamethasone");
    Glioblastoma.add("Levetiracetam");
    Glioblastoma.add("Phenytoin");

}